### ISSUE TITLE
anweber.vscode-tidyhtml-1.9.0/tidy/{darwin,linux,win32}/tiny is not executable - and so - useless!

### ISSUE THREAD

**Issue by soenkekluth** [AnWeber/vscode-tidyhtml#18] opened 2018-03-02 05:28 UTC
~/.vscode/extensions/anweber.vscode-tidyhtml-1.9.0/out/src/../../tidy/darwin/tidy) is not usable. Please configure tidyHtml.tidyExecPath.

the error message is also an error itself.

please do a ``chmod +x tidy`` on each of your tidy.

i configured the path instead to tidy on my machine - well guess what?  ``/usr/local/bin/tidy``
this does not even change the error message and is just wrong solved.. "please configure"

**Comment by AnWeber** [comment] 2018-03-02 07:07
You are right. I will fix it immediately. Thanks.

**Comment by AnWeber** [comment] 2018-03-02 07:08
duplicate of #17

**Closed as completed by AnWeber** 2018-03-02 07:08 UTC
